name: "Hyuga"
description: "Auto parse key value vault to env"
author: "akwanmaroso"

inputs:
  VAULT_ADDRESS:
    description: "Address of vault deployed"
    required: true
  VAULT_TOKEN:
    description: "Token for authentication"
    required: true
  SECRET_PATH:
    description: "Path into the secret"
    required: true
  KV_MOUNT_PATH:
    description: "KV engine mount path"
    required: false
    default: "kv"

runs:
  using: "docker"
  image: "docker://akwanmaroso/hyuga:v-1.2.0"
  env:
    VAULT_ADDRESS: ${{ inputs.VAULT_ADDRESS }}
    VAULT_TOKEN: ${{ inputs.VAULT_TOKEN }}
    SECRET_PATH: ${{ inputs.SECRET_PATH }}
    KV_MOUNT_PATH: ${{ inputs.KV_MOUNT_PATH }}
