name: "Hyuga"
description: "Auto parse key value vault to env"
author: "akwanmaroso"

inputs:
  VAULT_ADDRESS:
    description: "Address of vault deployed"
    required: true
  VAULT_TOKEN:
    description: "Token for authentication"
    required: true
  SECRET_PATH:
    description: "Path into the secret"
    required: true

runs:
  using: "docker"
  image: "docker://akwanmaroso/hyuga:latest"
