name: Build and Push

on:
  push:
    tags:
      - "v-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build and push Docker image
        run: |
          docker build -t akwanmaroso/hyuga:${{ steps.extract_tag.outputs.tag }} .
          docker push akwanmaroso/hyuga:${{ steps.extract_tag.outputs.tag }}
